FROM node:12.14.0


#Environemnts
ENV host=18.184.46.63
ENV user=bitnami

# install nuxt to generate static content
COPY ./app/. /app/
COPY ./scripts/deploy.sh /scripts/deploy.sh

#TODO change ALERT SECURITY
COPY ./scripts/scp.pem /app/security/scp.pem
RUN chmod 400 /app/security/scp.pem

# install nuxt to generate static content
RUN npm install -g nuxt && npm run --prefix /app/ generate

RUN scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /app/security/scp.pem -r /app/dist/* bitnami@18.184.46.63:/home/bitnami/stack/nginx/html/